// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2nR8xql7EkkoBPBGb_bnRGnh6xrsTlk',
    appId: '1:70850232108:web:4b0dde7db77c9c513d3689',
    messagingSenderId: '70850232108',
    projectId: 'quanly-e5ea6',
    authDomain: 'quanly-e5ea6.firebaseapp.com',
    storageBucket: 'quanly-e5ea6.firebasestorage.app',
    measurementId: 'G-X8TPW9197C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpXewF-RXkobvQ5h1J2ZNN6np2nyit7_c',
    appId: '1:70850232108:android:e7c4320e7fc0dea23d3689',
    messagingSenderId: '70850232108',
    projectId: 'quanly-e5ea6',
    storageBucket: 'quanly-e5ea6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy2nR8xql7EkkoBPBGb_bnRGnh6xrsTlk',
    appId: '1:70850232108:web:140e49306033f7453d3689',
    messagingSenderId: '70850232108',
    projectId: 'quanly-e5ea6',
    authDomain: 'quanly-e5ea6.firebaseapp.com',
    storageBucket: 'quanly-e5ea6.firebasestorage.app',
    measurementId: 'G-J57PJ2WPJK',
  );
}
